"""email_verification_table

Revision ID: d3b1a2eca731
Revises: 4e460cd34fea
Create Date: 2023-08-27 10:53:35.221136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b1a2eca731'
down_revision: Union[str, None] = '4e460cd34fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Email_Varification',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.add_column('User', sa.Column('verification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'verification')
    op.drop_table('Email_Varification')
    # ### end Alembic commands ###
